workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push' || $CI_PIPELINE_SOURCE == 'web_push_event' || $CI_COMMIT_BRANCH == 'main'

image: python:3.12


stages:
  - build
  - test
  - lint


before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

unittest:
  stage: test
  script:
    - pytest tests

mypy:
  stage: test
  script:
    - mypy src/

black:
  stage: test
  script:
    - black --diff --check src/

isort:
  stage: test
  script:
    - isort --check-only src/

flake8:
  stage: test
  script:
    - flake8 src/